### ISSUE TITLE
setup.sh error

### ISSUE THREAD

**Issue by goat1398** [danthedeckie/streetsign#2]
I cannot get setup.sh to work no matter what.
![image](https://user-images.githubusercontent.com/39496076/60176385-c69b0600-981e-11e9-90fd-3f30348b2689.png)

**Comment by danthedeckie** [comment]
Hi @goat1398,

I just went through and updated it all to python3 just now, simplfying a few bits.

Try again from scratch with python3.7 or so, and see if it works now. 

Daniel
